server:
  port: 8083


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Yogesh@123
    driver-class-name: com.mysql.cj.jdbc.Driver


  config:
    import: configserver:http://localhost:8080

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health


  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 6s
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingRetry:
        max-attempts: 3
        wait-duration: 2s

  ratelimiter:
    instance:
      userRateLimiter:
        limit-refersh-period: 4s
        limit-for-period: 2
        timeout-duration: 0